export * from "./ifArray";
export * from "./ifBoolean";
export * from "./ifNumber";
export * from "./ifNotNull";
export * from "./ifSameType";
export * from "./ifContainer";
export * from "./ifHasKey";
export * from "./ifLength";
export * from "./ifScalar";
export * from "./ifNull";
export * from "./ifObject";
export * from "./ifTrue";
export * from "./ifFunction";
export * from "./ifFalse";
export * from "./ifChar";
export * from "./ifString";
export * from "./ifUndefined";
export * from "./ifArrayPartial";

