// reference: https://www.xe.com/en-us/symbols/

export const CURRENCY_LOOKUP = {
    "AED": { name: "UAE Dirham", family: "dirham", symbol: "د.إ", country: "United Arab Emirates", country_abbrev: "ARE" },
    "ARS": { name: "Argentine Peso", family: "peso", symbol: "$", country: "Argentina", country_abbrev: "ARG" },
    "AUD": { name: "Australian Dollar", family: "dollar", symbol: "$", country: "Australia", country_abbrev: "AUS" },
    "AZN": { name: "Azerbaijani Manat", family: null, symbol: "₼", country: "Azerbaijan", country_abbrev: "AZE" },
    "BDT": { name: "Bangladeshi Taka", family: null, symbol: "৳", country: "Bangladesh", country_abbrev: "BGD" },
    "BRL": { name: "Brazilian Real", family: null, symbol: "R$", country: "Brazil", country_abbrev: "BRA" },
    "BTC": { name: "Bitcoin", family: "crypto", symbol: "₿", country: "Global", country_abbrev: "ZZZ" },
    "CAD": { name: "Canadian Dollar", family: "dollar", symbol: "$", country: "Canada", country_abbrev: "CAN" },
    "CHF": { name: "Swiss Franc", family: "franc", symbol: "₣", country: "Switzerland", country_abbrev: "CHE" },
    "CLP": { name: "Chilean Peso", family: "peso", symbol: "$", country: "Chile", country_abbrev: "CHL" },
    "CNY": { name: "Chinese Yuan", family: "yuan", symbol: "¥", country: "China", country_abbrev: "CHN" },
    "COP": { name: "Colombian Peso", family: "peso", symbol: "$", country: "Colombia", country_abbrev: "COL" },
    "CRC": { name: "Costa Rican Colón", family: "colon", symbol: "₡", country: "Costa Rica", country_abbrev: "CRI" },
    "DKK": { name: "Danish Krone", family: "krone", symbol: "kr", country: "Denmark", country_abbrev: "DNK" },
    "EGP": { name: "Egyptian Pound", family: "pound", symbol: "£", country: "Egypt", country_abbrev: "EGY" },
    "EUR": { name: "Euro", family: null, symbol: "€", country: "European Union", country_abbrev: "EUR" },
    "GBP": { name: "British Pound", family: "pound", symbol: "£", country: "United Kingdom", country_abbrev: "GBR" },
    "GEL": { name: "Georgian Lari", family: null, symbol: "₾", country: "Georgia", country_abbrev: "GEO" },
    "GHS": { name: "Ghanaian Cedi", family: "cedi", symbol: "₵", country: "Ghana", country_abbrev: "GHA" },
    "HKD": { name: "Hong Kong Dollar", family: "dollar", symbol: "$", country: "Hong Kong", country_abbrev: "HKG" },
    "IDR": { name: "Indonesian Rupiah", family: "rupiah", symbol: "Rp", country: "Indonesia", country_abbrev: "IDN" },
    "ILS": { name: "Israeli Shekel", family: "shekel", symbol: "₪", country: "Israel", country_abbrev: "ISR" },
    "INR": { name: "Indian Rupee", family: "rupee", symbol: "₹", country: "India", country_abbrev: "IND" },
    "IRR": { name: "Iranian Rial", family: "rial", symbol: "﷼", country: "Iran", country_abbrev: "IRN" },
    "JPY": { name: "Japanese Yen", family: "yen", symbol: "¥", country: "Japan", country_abbrev: "JPN" },
    "KES": { name: "Kenyan Shilling", family: "shilling", symbol: "KSh", country: "Kenya", country_abbrev: "KEN" },
    "KRW": { name: "South Korean Won", family: "won", symbol: "₩", country: "South Korea", country_abbrev: "KOR" },
    "KZT": { name: "Kazakhstani Tenge", family: null, symbol: "₸", country: "Kazakhstan", country_abbrev: "KAZ" },
    "LKR": { name: "Sri Lankan Rupee", family: "rupee", symbol: "₨", country: "Sri Lanka", country_abbrev: "LKA" },
    "MXN": { name: "Mexican Peso", family: "peso", symbol: "$", country: "Mexico", country_abbrev: "MEX" },
    "MYR": { name: "Malaysian Ringgit", family: "ringgit", symbol: "RM", country: "Malaysia", country_abbrev: "MYS" },
    "NGN": { name: "Nigerian Naira", family: null, symbol: "₦", country: "Nigeria", country_abbrev: "NGA" },
    "NOK": { name: "Norwegian Krone", family: "krone", symbol: "kr", country: "Norway", country_abbrev: "NOR" },
    "NZD": { name: "New Zealand Dollar", family: "dollar", symbol: "$", country: "New Zealand", country_abbrev: "NZL" },
    "OMR": { name: "Omani Rial", family: "rial", symbol: "﷼", country: "Oman", country_abbrev: "OMN" },
    "PEN": { name: "Peruvian Sol", family: null, symbol: "S/", country: "Peru", country_abbrev: "PER" },
    "PKR": { name: "Pakistani Rupee", family: "rupee", symbol: "₨", country: "Pakistan", country_abbrev: "PAK" },
    "PLN": { name: "Polish Złoty", family: null, symbol: "zł", country: "Poland", country_abbrev: "POL" },
    "PYG": { name: "Paraguayan Guaraní", family: "guarani", symbol: "₲", country: "Paraguay", country_abbrev: "PRY" },
    "QAR": { name: "Qatari Riyal", family: "rial", symbol: "﷼", country: "Qatar", country_abbrev: "QAT" },
    "RUB": { name: "Russian Ruble", family: null, symbol: "₽", country: "Russia", country_abbrev: "RUS" },
    "SAR": { name: "Saudi Riyal", family: "rial", symbol: "﷼", country: "Saudi Arabia", country_abbrev: "SAU" },
    "SEK": { name: "Swedish Krona", family: "krone", symbol: "kr", country: "Sweden", country_abbrev: "SWE" },
    "SGD": { name: "Singapore Dollar", family: "dollar", symbol: "$", country: "Singapore", country_abbrev: "SGP" },
    "THB": { name: "Thai Baht", family: null, symbol: "฿", country: "Thailand", country_abbrev: "THA" },
    "TRY": { name: "Turkish Lira", family: null, symbol: "₺", country: "Turkey", country_abbrev: "TUR" },
    "UAH": { name: "Ukrainian Hryvnia", family: null, symbol: "₴", country: "Ukraine", country_abbrev: "UKR" },
    "USD": { name: "US Dollar", family: "dollar", symbol: "$", country: "United States", country_abbrev: "USA" },
    "UYU": { name: "Uruguayan Peso", family: "peso", symbol: "$U", country: "Uruguay", country_abbrev: "URY" },
    "UZS": { name: "Uzbekistani Som", family: null, symbol: "so'm", country: "Uzbekistan", country_abbrev: "UZB" },
    "VND": { name: "Vietnamese Dong", family: null, symbol: "₫", country: "Vietnam", country_abbrev: "VNM" },
    "ZAR": { name: "South African Rand", family: "rand", symbol: "R", country: "South Africa", country_abbrev: "ZAF" }
} as const;
