export const HEMISPHERE = ["northern", "southern"] as const;

/**
 * The continents on planet earth
 */
export const CONTINENTS = [
    "Africa",
    "Australia",
    "Antarctica",
    "Asia",
    "Europe",
    "North America",
    "South America",
] as const;

/**
 * The 50 US states: `[name, abbrev, true]`
 */
export const US_STATE_LOOKUP_STRICT = [
    { name: "Alabama", abbrev: "AL" },
    { name: "Alaska", abbrev: "AK" },
    { name: "Arizona", abbrev: "AZ" },
    { name: "Arkansas", abbrev: "AR" },
    { name: "California", abbrev: "CA" },
    { name: "Colorado", abbrev: "CO" },
    { name: "Connecticut", abbrev: "CT" },
    { name: "Delaware", abbrev: "DE" },
    { name: "Florida", abbrev: "FL" },
    { name: "Georgia", abbrev: "GA" },
    { name: "Hawaii", abbrev: "HI" },
    { name: "Idaho", abbrev: "ID" },
    { name: "Illinois", abbrev: "IL" },
    { name: "Indiana", abbrev: "IN" },
    { name: "Iowa", abbrev: "IA" },
    { name: "Kansas", abbrev: "KS" },
    { name: "Kentucky", abbrev: "KY" },
    { name: "Louisiana", abbrev: "LA" },
    { name: "Maine", abbrev: "ME" },
    { name: "Maryland", abbrev: "MD" },
    { name: "Massachusetts", abbrev: "MA" },
    { name: "Michigan", abbrev: "MI" },
    { name: "Minnesota", abbrev: "MN" },
    { name: "Mississippi", abbrev: "MS" },
    { name: "Missouri", abbrev: "MO" },
    { name: "Montana", abbrev: "MT" },
    { name: "Nebraska", abbrev: "NE" },
    { name: "Nevada", abbrev: "NV" },
    { name: "New Hampshire", abbrev: "NH" },
    { name: "New Jersey", abbrev: "NJ" },
    { name: "New Mexico", abbrev: "NM" },
    { name: "New York", abbrev: "NY" },
    { name: "North Carolina", abbrev: "NC" },
    { name: "North Dakota", abbrev: "ND" },
    { name: "Ohio", abbrev: "OH" },
    { name: "Oklahoma", abbrev: "OK" },
    { name: "Oregon", abbrev: "OR" },
    { name: "Pennsylvania", abbrev: "PA" },
    { name: "Rhode Island", abbrev: "RI" },
    { name: "South Carolina", abbrev: "SC" },
    { name: "South Dakota", abbrev: "SD" },
    { name: "Tennessee", abbrev: "TN" },
    { name: "Texas", abbrev: "TX" },
    { name: "Utah", abbrev: "UT" },
    { name: "Vermont", abbrev: "VT" },
    { name: "Virginia", abbrev: "VA" },
    { name: "Washington", abbrev: "WA" },
    { name: "West Virginia", abbrev: "WV" },
    { name: "Wisconsin", abbrev: "WI" },
    { name: "Wyoming", abbrev: "WY" },
] as const;

/**
 * The 9 provinces to the US which are granted State codes.
 */
export const US_STATE_LOOKUP_PROVINCES = [
    { name: "Puerto Rico", abbrev: "PR" },
    { name: "Virgin Islands", abbrev: "VI" },
    { name: "Palau", abbrev: "PW" },
    { name: "Federated States of Micronesia", abbrev: "FM" },
    { name: "Northern Mariana Islands", abbrev: "MP" },
    { name: "District of Columbia", abbrev: "DC" },
    { name: "Marshall Islands", abbrev: "MH" },
    { name: "American Samoa", abbrev: "AS" },
    { name: "Guam", abbrev: "GU" },
] as const;

/**
 * All 50 states and 9 provinces which have State abbreviations.
 *
 * Data format is: `[name, abbrev, flag]` where the boolean flag
 * indicates whether the line item is one of the 50 true states.
 */
export const US_STATE_LOOKUP = [
    ...US_STATE_LOOKUP_STRICT,
    ...US_STATE_LOOKUP_PROVINCES,
] as const;

/**
 * A lookup which provides a list of state abbreviations associated
 * with the first digit of the zip code.
 */
export const ZIP_TO_STATE = {
    0: ["CT", "MA", "ME", "NH", "NJ", "NY", "PR", "RI", "VT", "VI"],
    1: ["DE", "NY", "PA"],
    2: ["DC", "MD", "NC", "SC", "VA", "WV"],
    3: ["AL", "FL", "GA", "MS", "TN"],
    4: ["IN", "KY", "MI", "OH"],
    5: ["IA", "MN", "MT", "ND", "SD", "WI"],
    6: ["IL", "KS", "MO", "NE"],
    7: ["AR", "LA", "OK", "TX"],
    8: ["AZ", "CO", "ID", "NM", "NV", "UT", "WY"],
    9: ["AK", "AS", "CA", "GU", "HI", "MH", "FM", "MP", "OR", "PW", "WA"],
} as const;

/**
 * Languages with current ISO 639 Set 1 (two-letter) codes, ordered by Set 1 code.
 * Set 2 uses the terminological (ISO 639-2/T) code where variants exist.
 *
 * @see https://www.loc.gov/standards/iso639-2/ISO-639-2_utf-8.txt
 */
export const LOCALES = [
    { set1: "aa", set2: "aar", language: "Afar" },
    { set1: "ab", set2: "abk", language: "Abkhazian" },
    { set1: "ae", set2: "ave", language: "Avestan" },
    { set1: "af", set2: "afr", language: "Afrikaans" },
    { set1: "ak", set2: "aka", language: "Akan" },
    { set1: "am", set2: "amh", language: "Amharic" },
    { set1: "an", set2: "arg", language: "Aragonese" },
    { set1: "ar", set2: "ara", language: "Arabic" },
    { set1: "as", set2: "asm", language: "Assamese" },
    { set1: "av", set2: "ava", language: "Avaric" },
    { set1: "ay", set2: "aym", language: "Aymara" },
    { set1: "az", set2: "aze", language: "Azerbaijani" },
    { set1: "ba", set2: "bak", language: "Bashkir" },
    { set1: "be", set2: "bel", language: "Belarusian" },
    { set1: "bg", set2: "bul", language: "Bulgarian" },
    { set1: "bi", set2: "bis", language: "Bislama" },
    { set1: "bm", set2: "bam", language: "Bambara" },
    { set1: "bn", set2: "ben", language: "Bengali" },
    { set1: "bo", set2: "bod", language: "Tibetan" },
    { set1: "br", set2: "bre", language: "Breton" },
    { set1: "bs", set2: "bos", language: "Bosnian" },
    { set1: "ca", set2: "cat", language: "Catalan; Valencian" },
    { set1: "ce", set2: "che", language: "Chechen" },
    { set1: "ch", set2: "cha", language: "Chamorro" },
    { set1: "co", set2: "cos", language: "Corsican" },
    { set1: "cr", set2: "cre", language: "Cree" },
    { set1: "cs", set2: "ces", language: "Czech" },
    {
        set1: "cu",
        set2: "chu",
        language:
            "Church Slavic; Old Slavonic; Church Slavonic; Old Bulgarian; Old Church Slavonic",
    },
    { set1: "cv", set2: "chv", language: "Chuvash" },
    { set1: "cy", set2: "cym", language: "Welsh" },
    { set1: "da", set2: "dan", language: "Danish" },
    { set1: "de", set2: "deu", language: "German" },
    { set1: "dv", set2: "div", language: "Divehi; Dhivehi; Maldivian" },
    { set1: "dz", set2: "dzo", language: "Dzongkha" },
    { set1: "ee", set2: "ewe", language: "Ewe" },
    { set1: "el", set2: "ell", language: "Modern Greek (1453-)" },
    { set1: "en", set2: "eng", language: "English" },
    { set1: "eo", set2: "epo", language: "Esperanto" },
    { set1: "es", set2: "spa", language: "Spanish; Castilian" },
    { set1: "et", set2: "est", language: "Estonian" },
    { set1: "eu", set2: "eus", language: "Basque" },
    { set1: "fa", set2: "fas", language: "Persian" },
    { set1: "ff", set2: "ful", language: "Fulah" },
    { set1: "fi", set2: "fin", language: "Finnish" },
    { set1: "fj", set2: "fij", language: "Fijian" },
    { set1: "fo", set2: "fao", language: "Faroese" },
    { set1: "fr", set2: "fra", language: "French" },
    { set1: "fy", set2: "fry", language: "Western Frisian" },
    { set1: "ga", set2: "gle", language: "Irish" },
    { set1: "gd", set2: "gla", language: "Gaelic; Scottish Gaelic" },
    { set1: "gl", set2: "glg", language: "Galician" },
    { set1: "gn", set2: "grn", language: "Guarani" },
    { set1: "gu", set2: "guj", language: "Gujarati" },
    { set1: "gv", set2: "glv", language: "Manx" },
    { set1: "ha", set2: "hau", language: "Hausa" },
    { set1: "he", set2: "heb", language: "Hebrew" },
    { set1: "hi", set2: "hin", language: "Hindi" },
    { set1: "ho", set2: "hmo", language: "Hiri Motu" },
    { set1: "hr", set2: "hrv", language: "Croatian" },
    { set1: "ht", set2: "hat", language: "Haitian; Haitian Creole" },
    { set1: "hu", set2: "hun", language: "Hungarian" },
    { set1: "hy", set2: "hye", language: "Armenian" },
    { set1: "hz", set2: "her", language: "Herero" },
    {
        set1: "ia",
        set2: "ina",
        language: "Interlingua (International Auxiliary Language Association)",
    },
    { set1: "id", set2: "ind", language: "Indonesian" },
    { set1: "ie", set2: "ile", language: "Interlingue; Occidental" },
    { set1: "ig", set2: "ibo", language: "Igbo" },
    { set1: "ii", set2: "iii", language: "Sichuan Yi; Nuosu" },
    { set1: "ik", set2: "ipk", language: "Inupiaq" },
    { set1: "io", set2: "ido", language: "Ido" },
    { set1: "is", set2: "isl", language: "Icelandic" },
    { set1: "it", set2: "ita", language: "Italian" },
    { set1: "iu", set2: "iku", language: "Inuktitut" },
    { set1: "ja", set2: "jpn", language: "Japanese" },
    { set1: "jv", set2: "jav", language: "Javanese" },
    { set1: "ka", set2: "kat", language: "Georgian" },
    { set1: "kg", set2: "kon", language: "Kongo" },
    { set1: "ki", set2: "kik", language: "Kikuyu; Gikuyu" },
    { set1: "kj", set2: "kua", language: "Kuanyama; Kwanyama" },
    { set1: "kk", set2: "kaz", language: "Kazakh" },
    { set1: "kl", set2: "kal", language: "Kalaallisut; Greenlandic" },
    { set1: "km", set2: "khm", language: "Central Khmer" },
    { set1: "kn", set2: "kan", language: "Kannada" },
    { set1: "ko", set2: "kor", language: "Korean" },
    { set1: "kr", set2: "kau", language: "Kanuri" },
    { set1: "ks", set2: "kas", language: "Kashmiri" },
    { set1: "ku", set2: "kur", language: "Kurdish" },
    { set1: "kv", set2: "kom", language: "Komi" },
    { set1: "kw", set2: "cor", language: "Cornish" },
    { set1: "ky", set2: "kir", language: "Kirghiz; Kyrgyz" },
    { set1: "la", set2: "lat", language: "Latin" },
    { set1: "lb", set2: "ltz", language: "Luxembourgish; Letzeburgesch" },
    { set1: "lg", set2: "lug", language: "Ganda" },
    { set1: "li", set2: "lim", language: "Limburgan; Limburger; Limburgish" },
    { set1: "ln", set2: "lin", language: "Lingala" },
    { set1: "lo", set2: "lao", language: "Lao" },
    { set1: "lt", set2: "lit", language: "Lithuanian" },
    { set1: "lu", set2: "lub", language: "Luba-Katanga" },
    { set1: "lv", set2: "lav", language: "Latvian" },
    { set1: "mg", set2: "mlg", language: "Malagasy" },
    { set1: "mh", set2: "mah", language: "Marshallese" },
    { set1: "mi", set2: "mri", language: "Maori" },
    { set1: "mk", set2: "mkd", language: "Macedonian" },
    { set1: "ml", set2: "mal", language: "Malayalam" },
    { set1: "mn", set2: "mon", language: "Mongolian" },
    { set1: "mr", set2: "mar", language: "Marathi" },
    { set1: "ms", set2: "msa", language: "Malay" },
    { set1: "mt", set2: "mlt", language: "Maltese" },
    { set1: "my", set2: "mya", language: "Burmese" },
    { set1: "na", set2: "nau", language: "Nauru" },
    { set1: "nb", set2: "nob", language: "Norwegian Bokmål" },
    { set1: "nd", set2: "nde", language: "North Ndebele" },
    { set1: "ne", set2: "nep", language: "Nepali" },
    { set1: "ng", set2: "ndo", language: "Ndonga" },
    { set1: "nl", set2: "nld", language: "Dutch; Flemish" },
    { set1: "nn", set2: "nno", language: "Norwegian Nynorsk" },
    { set1: "no", set2: "nor", language: "Norwegian" },
    { set1: "nr", set2: "nbl", language: "South Ndebele" },
    { set1: "nv", set2: "nav", language: "Navajo; Navaho" },
    { set1: "ny", set2: "nya", language: "Chichewa; Chewa; Nyanja" },
    { set1: "oc", set2: "oci", language: "Occitan (post 1500)" },
    { set1: "oj", set2: "oji", language: "Ojibwa" },
    { set1: "om", set2: "orm", language: "Oromo" },
    { set1: "or", set2: "ori", language: "Oriya" },
    { set1: "os", set2: "oss", language: "Ossetian; Ossetic" },
    { set1: "pa", set2: "pan", language: "Panjabi; Punjabi" },
    { set1: "pi", set2: "pli", language: "Pali" },
    { set1: "pl", set2: "pol", language: "Polish" },
    { set1: "ps", set2: "pus", language: "Pushto; Pashto" },
    { set1: "pt", set2: "por", language: "Portuguese" },
    { set1: "qu", set2: "que", language: "Quechua" },
    { set1: "rm", set2: "roh", language: "Romansh" },
    { set1: "rn", set2: "run", language: "Rundi" },
    { set1: "ro", set2: "ron", language: "Romanian; Moldavian; Moldovan" },
    { set1: "ru", set2: "rus", language: "Russian" },
    { set1: "rw", set2: "kin", language: "Kinyarwanda" },
    { set1: "sa", set2: "san", language: "Sanskrit" },
    { set1: "sc", set2: "srd", language: "Sardinian" },
    { set1: "sd", set2: "snd", language: "Sindhi" },
    { set1: "se", set2: "sme", language: "Northern Sami" },
    { set1: "sg", set2: "sag", language: "Sango" },
    { set1: "si", set2: "sin", language: "Sinhala; Sinhalese" },
    { set1: "sk", set2: "slk", language: "Slovak" },
    { set1: "sl", set2: "slv", language: "Slovenian" },
    { set1: "sm", set2: "smo", language: "Samoan" },
    { set1: "sn", set2: "sna", language: "Shona" },
    { set1: "so", set2: "som", language: "Somali" },
    { set1: "sq", set2: "sqi", language: "Albanian" },
    { set1: "sr", set2: "srp", language: "Serbian" },
    { set1: "ss", set2: "ssw", language: "Swati" },
    { set1: "st", set2: "sot", language: "Sotho, Southern" },
    { set1: "su", set2: "sun", language: "Sundanese" },
    { set1: "sv", set2: "swe", language: "Swedish" },
    { set1: "sw", set2: "swa", language: "Swahili" },
    { set1: "ta", set2: "tam", language: "Tamil" },
    { set1: "te", set2: "tel", language: "Telugu" },
    { set1: "tg", set2: "tgk", language: "Tajik" },
    { set1: "th", set2: "tha", language: "Thai" },
    { set1: "ti", set2: "tir", language: "Tigrinya" },
    { set1: "tk", set2: "tuk", language: "Turkmen" },
    { set1: "tl", set2: "tgl", language: "Tagalog" },
    { set1: "tn", set2: "tsn", language: "Tswana" },
    { set1: "to", set2: "ton", language: "Tonga (Tonga Islands)" },
    { set1: "tr", set2: "tur", language: "Turkish" },
    { set1: "ts", set2: "tso", language: "Tsonga" },
    { set1: "tt", set2: "tat", language: "Tatar" },
    { set1: "tw", set2: "twi", language: "Twi" },
    { set1: "ty", set2: "tah", language: "Tahitian" },
    { set1: "ug", set2: "uig", language: "Uighur; Uyghur" },
    { set1: "uk", set2: "ukr", language: "Ukrainian" },
    { set1: "ur", set2: "urd", language: "Urdu" },
    { set1: "uz", set2: "uzb", language: "Uzbek" },
    { set1: "ve", set2: "ven", language: "Venda" },
    { set1: "vi", set2: "vie", language: "Vietnamese" },
    { set1: "vo", set2: "vol", language: "Volapük" },
    { set1: "wa", set2: "wln", language: "Walloon" },
    { set1: "wo", set2: "wol", language: "Wolof" },
    { set1: "xh", set2: "xho", language: "Xhosa" },
    { set1: "yi", set2: "yid", language: "Yiddish" },
    { set1: "yo", set2: "yor", language: "Yoruba" },
    { set1: "za", set2: "zha", language: "Zhuang; Chuang" },
    { set1: "zh", set2: "zho", language: "Chinese" },
    { set1: "zu", set2: "zul", language: "Zulu" },
] as const satisfies {
    set1: string;
    set2: string;
    language: string;
}[];
