/**
 * All country codes (name, alpha-2, country-code)
 */
export const ISO3166_1 = [
  { name: "Afghanistan", alpha2: "AF", countryCode: "004", alpha3: "AFG" },
  { name: "Albania", alpha2: "AL", countryCode: "008", alpha3: "ALB" },
  { name: "Algeria", alpha2: "DZ", countryCode: "012", alpha3: "DZA" },
  { name: "Andorra", alpha2: "AD", countryCode: "020", alpha3: "AND" },
  { name: "Angola", alpha2: "AO", countryCode: "024", alpha3: "AGO" },
  { name: "Argentina", alpha2: "AR", countryCode: "032", alpha3: "ARG" },
  { name: "Australia", alpha2: "AU", countryCode: "036", alpha3: "AUS" },
  { name: "Austria", alpha2: "AT", countryCode: "040", alpha3: "AUT" },
  { name: "Azerbaijan", alpha2: "AZ", countryCode: "031", alpha3: "AZE" },
  { name: "Bahamas", alpha2: "BS", countryCode: "044", alpha3: "BHS" },
  { name: "Bangladesh", alpha2: "BD", countryCode: "050", alpha3: "BGD" },
  { name: "Belgium", alpha2: "BE", countryCode: "056", alpha3: "BEL" },
  { name: "Belize", alpha2: "BZ", countryCode: "084", alpha3: "BLZ" },
  { name: "Benin", alpha2: "BJ", countryCode: "204", alpha3: "BEN" },
  { name: "Bhutan", alpha2: "BT", countryCode: "064", alpha3: "BTN" },
  { name: "Bolivia", alpha2: "BO", countryCode: "068", alpha3: "BOL" },
  { name: "Bosnia and Herzegovina", alpha2: "BA", countryCode: "070", alpha3: "BIH" },
  { name: "Botswana", alpha2: "BW", countryCode: "072", alpha3: "BWA" },
  { name: "Brazil", alpha2: "BR", countryCode: "076", alpha3: "BRA" },
  { name: "Brunei Darussalam", alpha2: "BN", countryCode: "096", alpha3: "BRN" },
  { name: "Bulgaria", alpha2: "BG", countryCode: "100", alpha3: "BGR" },
  { name: "Burkina Faso", alpha2: "BF", countryCode: "854", alpha3: "BFA" },
  { name: "Burundi", alpha2: "BI", countryCode: "108", alpha3: "BDI" },
  { name: "Cambodia", alpha2: "KH", countryCode: "116", alpha3: "KHM" },
  { name: "Cameroon", alpha2: "CM", countryCode: "120", alpha3: "CMR" },
  { name: "Canada", alpha2: "CA", countryCode: "124", alpha3: "CAN" },
  { name: "Afghanistan", alpha2: "AF", countryCode: "004", alpha3: "AFG" },
  { name: "Albania", alpha2: "AL", countryCode: "008", alpha3: "ALB" },
  { name: "Algeria", alpha2: "DZ", countryCode: "012", alpha3: "DZA" },
  { name: "Andorra", alpha2: "AD", countryCode: "020", alpha3: "AND" },
  { name: "Angola", alpha2: "AO", countryCode: "024", alpha3: "AGO" },
  { name: "Argentina", alpha2: "AR", countryCode: "032", alpha3: "ARG" },
  { name: "Australia", alpha2: "AU", countryCode: "036", alpha3: "AUS" },
  { name: "Austria", alpha2: "AT", countryCode: "040", alpha3: "AUT" },
  { name: "Azerbaijan", alpha2: "AZ", countryCode: "031", alpha3: "AZE" },
  { name: "Bahamas", alpha2: "BS", countryCode: "044", alpha3: "BHS" },
  { name: "Bangladesh", alpha2: "BD", countryCode: "050", alpha3: "BGD" },
  { name: "Belgium", alpha2: "BE", countryCode: "056", alpha3: "BEL" },
  { name: "Belize", alpha2: "BZ", countryCode: "084", alpha3: "BLZ" },
  { name: "Benin", alpha2: "BJ", countryCode: "204", alpha3: "BEN" },
  { name: "Bhutan", alpha2: "BT", countryCode: "064", alpha3: "BTN" },
  { name: "Bolivia", alpha2: "BO", countryCode: "068", alpha3: "BOL" },
  { name: "Bosnia and Herzegovina", alpha2: "BA", countryCode: "070", alpha3: "BIH" },
  { name: "Botswana", alpha2: "BW", countryCode: "072", alpha3: "BWA" },
  { name: "Brazil", alpha2: "BR", countryCode: "076", alpha3: "BRA" },
  { name: "Brunei Darussalam", alpha2: "BN", countryCode: "096", alpha3: "BRN" },
  { name: "Bulgaria", alpha2: "BG", countryCode: "100", alpha3: "BGR" },
  { name: "Burkina Faso", alpha2: "BF", countryCode: "854", alpha3: "BFA" },
  { name: "Burundi", alpha2: "BI", countryCode: "108", alpha3: "BDI" },
  { name: "Cambodia", alpha2: "KH", countryCode: "116", alpha3: "KHM" },
  { name: "Cameroon", alpha2: "CM", countryCode: "120", alpha3: "CMR" },
  { name: "Canada", alpha2: "CA", countryCode: "124", alpha3: "CAN" },
  { name: "Maldives", alpha2: "MV", countryCode: "462", alpha3: "MDV" },
  { name: "Mali", alpha2: "ML", countryCode: "466", alpha3: "MLI" },
  { name: "Malta", alpha2: "MT", countryCode: "470", alpha3: "MLT" },
  { name: "Marshall Islands", alpha2: "MH", countryCode: "584", alpha3: "MHL" },
  { name: "Mauritania", alpha2: "MR", countryCode: "478", alpha3: "MRT" },
  { name: "Mauritius", alpha2: "MU", countryCode: "480", alpha3: "MUS" },
  { name: "Mexico", alpha2: "MX", countryCode: "484", alpha3: "MEX" },
  { name: "Micronesia (Federated States of)", alpha2: "FM", countryCode: "583", alpha3: "FSM" },
  { name: "Moldova (Republic of)", alpha2: "MD", countryCode: "498", alpha3: "MDA" },
  { name: "Monaco", alpha2: "MC", countryCode: "492", alpha3: "MCO" },
  { name: "Mongolia", alpha2: "MN", countryCode: "496", alpha3: "MNG" },
  { name: "Montenegro", alpha2: "ME", countryCode: "499", alpha3: "MNE" },
  { name: "Morocco", alpha2: "MA", countryCode: "504", alpha3: "MAR" },
  { name: "Mozambique", alpha2: "MZ", countryCode: "508", alpha3: "MOZ" },
  { name: "Myanmar", alpha2: "MM", countryCode: "104", alpha3: "MMR" },
  { name: "Namibia", alpha2: "NA", countryCode: "516", alpha3: "NAM" },
  { name: "Nauru", alpha2: "NR", countryCode: "520", alpha3: "NRU" },
  { name: "Nepal", alpha2: "NP", countryCode: "524", alpha3: "NPL" },
  { name: "Netherlands", alpha2: "NL", countryCode: "528", alpha3: "NLD" },
  { name: "New Zealand", alpha2: "NZ", countryCode: "554", alpha3: "NZL" },
  { name: "Nicaragua", alpha2: "NI", countryCode: "558", alpha3: "NIC" },
  { name: "Niger", alpha2: "NE", countryCode: "562", alpha3: "NER" },
  { name: "Nigeria", alpha2: "NG", countryCode: "566", alpha3: "NGA" },
  { name: "North Macedonia", alpha2: "MK", countryCode: "807", alpha3: "MKD" },
  { name: "Norway", alpha2: "NO", countryCode: "578", alpha3: "NOR" },
  { name: "Oman", alpha2: "OM", countryCode: "512", alpha3: "OMN" },
  { name: "Pakistan", alpha2: "PK", countryCode: "586", alpha3: "PAK" },
  { name: "Palau", alpha2: "PW", countryCode: "585", alpha3: "PLW" },
  { name: "Panama", alpha2: "PA", countryCode: "591", alpha3: "PAN" },
  { name: "Papua New Guinea", alpha2: "PG", countryCode: "598", alpha3: "PNG" },
  { name: "Paraguay", alpha2: "PY", countryCode: "600", alpha3: "PRY" },
  { name: "Peru", alpha2: "PE", countryCode: "604", alpha3: "PER" },
  { name: "Philippines", alpha2: "PH", countryCode: "608", alpha3: "PHL" },
  { name: "Poland", alpha2: "PL", countryCode: "616", alpha3: "POL" },
  { name: "Portugal", alpha2: "PT", countryCode: "620", alpha3: "PRT" },
  { name: "Qatar", alpha2: "QA", countryCode: "634", alpha3: "QAT" },
  { name: "Romania", alpha2: "RO", countryCode: "642", alpha3: "ROU" },
  { name: "Russian Federation", alpha2: "RU", countryCode: "643", alpha3: "RUS" },
  { name: "Rwanda", alpha2: "RW", countryCode: "646", alpha3: "RWA" },
  { name: "Saint Kitts and Nevis", alpha2: "KN", countryCode: "659", alpha3: "KNA" },
  { name: "Saint Lucia", alpha2: "LC", countryCode: "662", alpha3: "LCA" },
  { name: "Saint Vincent and the Grenadines", alpha2: "VC", countryCode: "670", alpha3: "VCT" },
  { name: "Samoa", alpha2: "WS", countryCode: "882", alpha3: "WSM" },
  { name: "San Marino", alpha2: "SM", countryCode: "674", alpha3: "SMR" },
  { name: "Sao Tome and Principe", alpha2: "ST", countryCode: "678", alpha3: "STP" },
  { name: "Saudi Arabia", alpha2: "SA", countryCode: "682", alpha3: "SAU" },
  { name: "Senegal", alpha2: "SN", countryCode: "686", alpha3: "SEN" },
  { name: "Serbia", alpha2: "RS", countryCode: "688", alpha3: "SRB" },
  { name: "Seychelles", alpha2: "SC", countryCode: "690", alpha3: "SYC" },
  { name: "Sierra Leone", alpha2: "SL", countryCode: "694", alpha3: "SLE" },
  { name: "Singapore", alpha2: "SG", countryCode: "702", alpha3: "SGP" },
  { name: "Slovakia", alpha2: "SK", countryCode: "703", alpha3: "SVK" },
  { name: "Slovenia", alpha2: "SI", countryCode: "705", alpha3: "SVN" },
  { name: "Solomon Islands", alpha2: "SB", countryCode: "090", alpha3: "SLB" },
  { name: "Somalia", alpha2: "SO", countryCode: "706", alpha3: "SOM" },
  { name: "South Africa", alpha2: "ZA", countryCode: "710", alpha3: "ZAF" },
  { name: "South Sudan", alpha2: "SS", countryCode: "728", alpha3: "SSD" },
  { name: "Spain", alpha2: "ES", countryCode: "724", alpha3: "ESP" },
  { name: "Sri Lanka", alpha2: "LK", countryCode: "144", alpha3: "LKA" },
  { name: "Sudan", alpha2: "SD", countryCode: "729", alpha3: "SDN" },
  { name: "Suriname", alpha2: "SR", countryCode: "740", alpha3: "SUR" },
  { name: "Sweden", alpha2: "SE", countryCode: "752", alpha3: "SWE" },
  { name: "Switzerland", alpha2: "CH", countryCode: "756", alpha3: "CHE" },
  { name: "Syrian Arab Republic", alpha2: "SY", countryCode: "760", alpha3: "SYR" },
  { name: "Taiwan", alpha2: "TW", countryCode: "158", alpha3: "TWN" },
  { name: "Tajikistan", alpha2: "TJ", countryCode: "762", alpha3: "TJK" },
  { name: "Tanzania", alpha2: "TZ", countryCode: "834", alpha3: "TZA" },
  { name: "Thailand", alpha2: "TH", countryCode: "764", alpha3: "THA" },
  { name: "Timor-Leste", alpha2: "TL", countryCode: "626", alpha3: "TLS" },
  { name: "Togo", alpha2: "TG", countryCode: "768", alpha3: "TGO" },
  { name: "Tonga", alpha2: "TO", countryCode: "776", alpha3: "TON" },
  { name: "Tonga", alpha2: "TO", countryCode: "776", alpha3: "TON" },
  { name: "Trinidad and Tobago", alpha2: "TT", countryCode: "780", alpha3: "TTO" },
  { name: "Tunisia", alpha2: "TN", countryCode: "788", alpha3: "TUN" },
  { name: "Turkey", alpha2: "TR", countryCode: "792", alpha3: "TUR" },
  { name: "Turkmenistan", alpha2: "TM", countryCode: "795", alpha3: "TKM" },
  { name: "Tuvalu", alpha2: "TV", countryCode: "798", alpha3: "TUV" },
  { name: "Uganda", alpha2: "UG", countryCode: "800", alpha3: "UGA" },
  { name: "Ukraine", alpha2: "UA", countryCode: "804", alpha3: "UKR" },
  { name: "United Arab Emirates", alpha2: "AE", countryCode: "784", alpha3: "ARE" },
  { name: "United Kingdom", alpha2: "GB", countryCode: "826", alpha3: "GBR" },
  { name: "United States of America", alpha2: "US", countryCode: "840", alpha3: "USA" },
  { name: "Uruguay", alpha2: "UY", countryCode: "858", alpha3: "URY" },
  { name: "Uzbekistan", alpha2: "UZ", countryCode: "860", alpha3: "UZB" },
  { name: "Vanuatu", alpha2: "VU", countryCode: "548", alpha3: "VUT" },
  { name: "Venezuela", alpha2: "VE", countryCode: "862", alpha3: "VEN" },
  { name: "Viet Nam", alpha2: "VN", countryCode: "704", alpha3: "VNM" },
  { name: "Yemen", alpha2: "YE", countryCode: "887", alpha3: "YEM" },
  { name: "Zambia", alpha2: "ZM", countryCode: "894", alpha3: "ZMB" },
  { name: "Zimbabwe", alpha2: "ZW", countryCode: "716", alpha3: "ZWE" },
] as const;
