export const US_NEWS = [
    { company: "New York Times", baseUrls: ["www.nytimes.com"] },
    { company: "CNN", baseUrls: ["www.cnn.com"] },
    { company: "Fox News", baseUrls: ["www.foxnews.com"] },
    { company: "NBC News", baseUrls: ["www.nbcnews.com", "www.msnbc.com"] },
    { company: "ABC News", baseUrls: ["abcnews.go.com"] },
    { company: "The Washington Post", baseUrls: ["www.washingtonpost.com"] },
    { company: "USA Today", baseUrls: ["www.usatoday.com"] },
    { company: "Bloomberg", baseUrls: ["www.bloomberg.com"] },
    { company: "NPR", baseUrls: ["www.npr.org"] },
    { company: "CBS News", baseUrls: ["www.cbsnews.com"] },
    { company: "The Wall Street Journal", baseUrls: ["www.wsj.com"] },
    { company: "Associated Press (AP)", baseUrls: ["www.apnews.com", "www.ap.org"] },
    { company: "Reuters", baseUrls: ["www.reuters.com"] },
    { company: "Newsweek", baseUrls: ["www.newsweek.com"] },
    { company: "Politico", baseUrls: ["www.politico.com"] },
    { company: "The Atlantic", baseUrls: ["www.theatlantic.com"] },
    { company: "Nexstar Media Group", baseUrls: ["www.nexstar.tv"] },
    { company: "PBS News", baseUrls: ["www.pbs.org"] },
    { company: "HuffPost", baseUrls: ["www.huffpost.com"] },
    { company: "The Boston Globe", baseUrls: ["www.bostonglobe.com"] },
] as const;

export const UK_NEWS = [
    { company: "BBC", baseUrls: ["www.bbc.co.uk", "www.bbc.com"] },
    { company: "The Guardian", baseUrls: ["www.theguardian.com/uk"] },
    { company: "The Daily Mail", baseUrls: ["www.dailymail.co.uk"] },
    { company: "The Sun", baseUrls: ["www.thesun.co.uk"] },
    { company: "The Times", baseUrls: ["www.thetimes.co.uk"] },
    { company: "Sky News", baseUrls: ["news.sky.com"] },
    { company: "The Telegraph", baseUrls: ["www.telegraph.co.uk"] },
    { company: "ITV News", baseUrls: ["www.itv.com/news"] },
    { company: "Financial Times", baseUrls: ["www.ft.com"] },
    { company: "Metro", baseUrls: ["www.metro.co.uk"] },
    { company: "The Independent", baseUrls: ["www.independent.co.uk"] },
    { company: "Evening Standard", baseUrls: ["www.standard.co.uk"] },
    { company: "Daily Mirror", baseUrls: ["www.mirror.co.uk"] },
    { company: "Channel 4 News", baseUrls: ["www.channel4.com/news"] },
    { company: "LBC", baseUrls: ["www.lbc.co.uk"] },
    { company: "Daily Express", baseUrls: ["www.express.co.uk"] },
    { company: "Birmingham Mail", baseUrls: ["www.birminghammail.co.uk"] },
    { company: "Manchester Evening News", baseUrls: ["www.manchestereveningnews.co.uk"] },
    { company: "The Scotsman", baseUrls: ["www.scotsman.com"] },
    { company: "Daily Record", baseUrls: ["www.dailyrecord.co.uk"] },
] as const;

export const GERMAN_NEWS = [
    { company: "BILD", baseUrls: ["www.bild.de"] },
    { company: "Die Zeit", baseUrls: ["www.zeit.de"] },
    { company: "Frankfurter Allgemeine Zeitung", baseUrls: ["www.faz.net"] },
    { company: "Süddeutsche Zeitung", baseUrls: ["www.sueddeutsche.de"] },
    { company: "Der Spiegel", baseUrls: ["www.spiegel.de"] },
    { company: "Die Welt", baseUrls: ["www.welt.de"] },
    { company: "Tagesschau", baseUrls: ["www.tagesschau.de"] },
    { company: "t-online", baseUrls: ["www.t-online.de"] },
    { company: "n-tv", baseUrls: ["www.n-tv.de"] },
    { company: "Handelsblatt", baseUrls: ["www.handelsblatt.com"] },
    { company: "Focus Online", baseUrls: ["www.focus.de"] },
    { company: "Frankfurter Rundschau", baseUrls: ["www.fr.de", "www.fr-online.de"] },
    { company: "taz - die tageszeitung", baseUrls: ["www.taz.de"] },
    { company: "Der Tagesspiegel", baseUrls: ["www.tagesspiegel.de"] },
    { company: "Rheinische Post", baseUrls: ["www.rp-online.de"] },
    { company: "Express", baseUrls: ["www.express.de"] },
    { company: "Münchner Merkur", baseUrls: ["www.merkur.de"] },
    { company: "Stuttgarter Zeitung", baseUrls: ["www.stuttgarter-zeitung.de"] },
    { company: "Hamburger Abendblatt", baseUrls: ["www.abendblatt.de"] },
    { company: "Deutsche Welle", baseUrls: ["www.dw.com"] },
] as const;

export const FRENCH_NEWS = [
    { company: "Le Figaro", baseUrls: ["www.lefigaro.fr"] },
    { company: "Le Monde", baseUrls: ["www.lemonde.fr"] },
    { company: "France 24", baseUrls: ["www.france24.com"] },
    { company: "Libération", baseUrls: ["www.liberation.fr"] },
    { company: "Les Echos", baseUrls: ["www.lesechos.fr"] },
    { company: "Ouest-France", baseUrls: ["www.ouest-france.fr"] },
    { company: "Le Parisien", baseUrls: ["www.leparisien.fr"] },
    { company: "Mediapart", baseUrls: ["www.mediapart.fr"] },
    { company: "L'Express", baseUrls: ["www.lexpress.fr"] },
    { company: "La Croix", baseUrls: ["www.la-croix.com"] },
    { company: "20 Minutes", baseUrls: ["www.20minutes.fr"] },
    { company: "Courrier International", baseUrls: ["www.courrierinternational.com"] },
    { company: "Le Point", baseUrls: ["www.lepoint.fr"] },
    { company: "Marianne", baseUrls: ["www.marianne.net"] },
    { company: "BFM TV", baseUrls: ["www.bfmtv.com"] },
    { company: "RTL France", baseUrls: ["www.rtl.fr"] },
    { company: "Charlie Hebdo", baseUrls: ["www.charliehebdo.fr"] },
    { company: "Challenges", baseUrls: ["www.challenges.fr"] },
    { company: "Télérama", baseUrls: ["www.telerama.fr"] },
    { company: "L'Obs", baseUrls: ["www.nouvelobs.com"] },
] as const;

export const CANADIAN_NEWS = [
    { company: "CBC News", baseUrls: ["www.cbc.ca"] },
    { company: "CTV News", baseUrls: ["www.ctvnews.ca"] },
    { company: "The Globe and Mail", baseUrls: ["www.theglobeandmail.com"] },
    { company: "Global News", baseUrls: ["www.globalnews.ca"] },
    { company: "Toronto Star", baseUrls: ["www.thestar.com"] },
    { company: "National Post", baseUrls: ["www.nationalpost.com"] },
    { company: "La Presse", baseUrls: ["www.lapresse.ca"] },
    { company: "Radio-Canada", baseUrls: ["ici.radio-canada.ca"] },
    { company: "The Canadian Press", baseUrls: ["www.thecanadianpress.com"] },
    { company: "Financial Post", baseUrls: ["financialpost.com"] },
    { company: "The Weather Network", baseUrls: ["www.theweathernetwork.com"] },
    { company: "Le Devoir", baseUrls: ["www.ledevoir.com"] },
    { company: "TVA Nouvelles", baseUrls: ["www.tvanouvelles.ca"] },
    { company: "Journal de Montréal", baseUrls: ["www.journaldemontreal.com"] },
    { company: "CityNews", baseUrls: ["www.citynews.ca"] },
    { company: "BNN Bloomberg", baseUrls: ["www.bnnbloomberg.ca"] },
    { company: "The Hamilton Spectator", baseUrls: ["www.thespec.com"] },
    { company: "Ottawa Citizen", baseUrls: ["ottawacitizen.com"] },
    { company: "Windsor Star", baseUrls: ["windsorstar.com"] },
    { company: "Edmonton Journal", baseUrls: ["edmontonjournal.com"] },
] as const;

export const DUTCH_NEWS = [
    { company: "Algemeen Dagblad (AD)", baseUrls: ["www.ad.nl"] },
    { company: "NOS", baseUrls: ["www.nos.nl"] },
    { company: "De Telegraaf", baseUrls: ["www.telegraaf.nl"] },
    { company: "NU.nl", baseUrls: ["www.nu.nl"] },
    { company: "Volkskrant", baseUrls: ["www.volkskrant.nl"] },
    { company: "NRC Handelsblad", baseUrls: ["www.nrc.nl"] },
    { company: "Trouw", baseUrls: ["www.trouw.nl"] },
    { company: "Het Parool", baseUrls: ["www.parool.nl"] },
    { company: "RTL Nieuws", baseUrls: ["www.rtlnieuws.nl"] },
    { company: "BNR Nieuwsradio", baseUrls: ["www.bnr.nl"] },
    { company: "Emerce", baseUrls: ["www.emerce.nl"] },
    { company: "VPRO", baseUrls: ["www.vpro.nl"] },
    { company: "De Gelderlander", baseUrls: ["www.gelderlander.nl"] },
    { company: "Friesch Dagblad", baseUrls: ["www.frieschdagblad.nl"] },
    { company: "De Stentor", baseUrls: ["www.destentor.nl"] },
    { company: "Metro Nieuws", baseUrls: ["www.metronieuws.nl"] },
    { company: "ANP", baseUrls: ["www.anp.nl"] },
    { company: "Dagblad van het Noorden", baseUrls: ["www.dvhn.nl"] },
    { company: "Reformatorisch Dagblad", baseUrls: ["www.rd.nl"] },
    { company: "Financieele Dagblad", baseUrls: ["www.fd.nl"] },
] as const;

export const ITALIAN_NEWS = [
    { company: "ANSA", baseUrls: ["www.ansa.it", "www.ansamed.info"] },
    { company: "Corriere della Sera", baseUrls: ["www.corriere.it"] },
    { company: "la Repubblica", baseUrls: ["www.repubblica.it"] },
    { company: "Il Sole 24 Ore", baseUrls: ["www.ilsole24ore.com"] },
    { company: "La Stampa", baseUrls: ["www.lastampa.it"] },
    { company: "Il Messaggero", baseUrls: ["www.ilmessaggero.it"] },
    { company: "Il Giornale", baseUrls: ["www.ilgiornale.it"] },
    { company: "Avvenire", baseUrls: ["www.avvenire.it"] },
    { company: "Il Fatto Quotidiano", baseUrls: ["www.ilfattoquotidiano.it"] },
    { company: "La Nazione", baseUrls: ["www.lanazione.it"] },
    { company: "TgCom24", baseUrls: ["www.tgcom24.mediaset.it"] },
    { company: "Sky TG24", baseUrls: ["tg24.sky.it"] },
    { company: "Rai News", baseUrls: ["www.rainews.it"] },
    { company: "Gazzetta dello Sport", baseUrls: ["www.gazzetta.it"] },
    { company: "Il Resto del Carlino", baseUrls: ["www.ilrestodelcarlino.it"] },
    { company: "Il Mattino", baseUrls: ["www.ilmattino.it"] },
    { company: "Il Secolo XIX", baseUrls: ["www.ilsecoloxix.it"] },
    { company: "Italia Oggi", baseUrls: ["www.italiaoggi.it"] },
    { company: "Libero", baseUrls: ["www.liberoquotidiano.it"] },
    { company: "Il Tirreno", baseUrls: ["www.iltirreno.it"] },
] as const;

export const BELGIUM_NEWS = [
    { company: "Het Laatste Nieuws (HLN)", baseUrls: ["www.hln.be"] },
    { company: "Nieuwsblad", baseUrls: ["www.nieuwsblad.be"] },
    { company: "RTBF", baseUrls: ["www.rtbf.be"] },
    { company: "Sudinfo", baseUrls: ["www.sudinfo.be"] },
    { company: "7sur7", baseUrls: ["www.7sur7.be"] },
    { company: "Le Soir", baseUrls: ["www.lesoir.be"] },
    { company: "De Standaard", baseUrls: ["www.standaard.be"] },
    { company: "VRT NWS", baseUrls: ["www.vrt.be"] },
    { company: "La Libre", baseUrls: ["www.lalibre.be"] },
    { company: "Gazet van Antwerpen", baseUrls: ["www.gva.be"] },
    { company: "Het Belang van Limburg", baseUrls: ["www.hbvl.be"] },
    { company: "De Morgen", baseUrls: ["www.demorgen.be"] },
    { company: "L'Avenir", baseUrls: ["www.lavenir.net"] },
    { company: "The Brussels Times", baseUrls: ["www.brusselstimes.com"] },
    { company: "Metro Belgique", baseUrls: ["nl.metrotime.be"] },
    { company: "Sudpresse", baseUrls: ["www.sudpress.be"] },
    { company: "Flamish Radio and TV Broadcasting Organization (VRT)", baseUrls: ["www.vrt.be"] },
    { company: "Knack", baseUrls: ["www.knack.be"] },
    { company: "De Tijd", baseUrls: ["www.tijd.be"] },
    { company: "BX1", baseUrls: ["www.bx1.be"] },
] as const;

export const MEXICAN_NEWS = [
    { company: "Televisa", baseUrls: ["www.televisa.news"] },
    { company: "El Universal", baseUrls: ["www.eluniversal.com.mx"] },
    { company: "Milenio", baseUrls: ["www.milenio.com"] },
    { company: "Excélsior", baseUrls: ["www.excelsior.com.mx"] },
    { company: "Reforma", baseUrls: ["www.reforma.com"] },
    { company: "La Jornada", baseUrls: ["www.jornada.com.mx"] },
    { company: "El Financiero", baseUrls: ["www.elfinanciero.com.mx"] },
    { company: "Proceso", baseUrls: ["www.proceso.com.mx"] },
    { company: "SDP Noticias", baseUrls: ["www.sdpnoticias.com"] },
    { company: "Diario de Yucatán", baseUrls: ["www.yucatan.com.mx"] },
    { company: "El Economista", baseUrls: ["www.eleconomista.com.mx"] },
    { company: "El Heraldo de México", baseUrls: ["www.heraldodemexico.com.mx"] },
    { company: "Noticieros Televisa", baseUrls: ["noticieros.televisa.com"] },
    { company: "Expansión", baseUrls: ["expansion.mx"] },
    { company: "La Razón", baseUrls: ["www.razon.com.mx"] },
    { company: "Noroeste", baseUrls: ["www.noroeste.com.mx"] },
    { company: "Uniradio Noticias", baseUrls: ["www.uniradionoticias.com"] },
    { company: "El Imparcial", baseUrls: ["www.elimparcial.com"] },
    { company: "Publimetro México", baseUrls: ["www.publimetro.com.mx"] },
    { company: "Notimex", baseUrls: ["www.notimex.gob.mx"] },
] as const;

export const SPANISH_NEWS = [
    { company: "El País", baseUrls: ["www.elpais.com"] },
    { company: "El Mundo", baseUrls: ["www.elmundo.es"] },
    { company: "ABC", baseUrls: ["www.abc.es"] },
    { company: "La Vanguardia", baseUrls: ["www.lavanguardia.com"] },
    { company: "El Confidencial", baseUrls: ["www.elconfidencial.com"] },
    { company: "La Razón", baseUrls: ["www.larazon.es"] },
    { company: "20 Minutos", baseUrls: ["www.20minutos.es"] },
    { company: "Agencia EFE", baseUrls: ["www.efe.com"] },
    { company: "Europa Press", baseUrls: ["www.europapress.es"] },
    { company: "Diario AS", baseUrls: ["www.as.com"] },
    { company: "Mundo Deportivo", baseUrls: ["www.mundodeportivo.com"] },
    { company: "El Periódico", baseUrls: ["www.elperiodico.com"] },
    { company: "Cinco Días", baseUrls: ["www.cincodias.com"] },
    { company: "Expansión", baseUrls: ["www.expansion.com"] },
    { company: "La Información", baseUrls: ["www.lainformacion.com"] },
    { company: "OK Diario", baseUrls: ["www.okdiario.com"] },
    { company: "Heraldo de Aragón", baseUrls: ["www.heraldo.es"] },
    { company: "Faro de Vigo", baseUrls: ["www.farodevigo.es"] },
    { company: "El Correo", baseUrls: ["www.elcorreo.com"] },
    { company: "Diario Sur", baseUrls: ["www.diariosur.es"] },
] as const;

export const INDIAN_NEWS = [
    { company: "The Times of India", baseUrls: ["timesofindia.indiatimes.com"] },
    { company: "The Hindu", baseUrls: ["www.thehindu.com"] },
    { company: "Hindustan Times", baseUrls: ["www.hindustantimes.com"] },
    { company: "NDTV", baseUrls: ["www.ndtv.com"] },
    { company: "India Today", baseUrls: ["www.indiatoday.in"] },
    { company: "Zee News", baseUrls: ["zeenews.india.com"] },
    { company: "Indian Express", baseUrls: ["indianexpress.com"] },
    { company: "The Economic Times", baseUrls: ["economictimes.indiatimes.com"] },
    { company: "Deccan Herald", baseUrls: ["www.deccanherald.com"] },
    { company: "DNA India", baseUrls: ["www.dnaindia.com"] },
    { company: "The Print", baseUrls: ["theprint.in"] },
    { company: "News18", baseUrls: ["www.news18.com"] },
    { company: "Scroll.in", baseUrls: ["scroll.in"] },
    { company: "Asian News International (ANI)", baseUrls: ["www.aninews.in"] },
    { company: "Outlook India", baseUrls: ["www.outlookindia.com"] },
    { company: "Business Standard", baseUrls: ["www.business-standard.com"] },
    { company: "Mint", baseUrls: ["www.livemint.com"] },
    { company: "OneIndia", baseUrls: ["www.oneindia.com"] },
    { company: "Quint", baseUrls: ["www.thequint.com"] },
    { company: "Free Press Journal", baseUrls: ["www.freepressjournal.in"] },
] as const;

export const CHINESE_NEWS = [
    { company: "Xinhua News Agency", baseUrls: ["www.xinhuanet.com"] },
    { company: "China Central Television (CCTV)", baseUrls: ["www.cctv.com"] },
    { company: "China Daily", baseUrls: ["www.chinadaily.com.cn"] },
    { company: "CGTN (China Global Television Network)", baseUrls: ["www.cgtn.com"] },
    { company: "People's Daily", baseUrls: ["www.people.cn"] },
    { company: "Global Times", baseUrls: ["www.globaltimes.cn"] },
    { company: "South China Morning Post", baseUrls: ["www.scmp.com"] },
    { company: "Shanghai Daily", baseUrls: ["www.shanghaidaily.com"] },
    { company: "China News Service", baseUrls: ["www.ecns.cn"] },
    { company: "Caixin", baseUrls: ["www.caixinglobal.com"] },
    { company: "The Paper", baseUrls: ["www.thepaper.cn"] },
    { company: "Yicai Global", baseUrls: ["www.yicaiglobal.com"] },
    { company: "Economic Daily", baseUrls: ["www.ce.cn"] },
    { company: "21st Century Business Herald", baseUrls: ["www.21jingji.com"] },
    { company: "Beijing Review", baseUrls: ["www.bjreview.com"] },
    { company: "China Economic Net", baseUrls: ["www.ce.cn"] },
    { company: "Tencent News", baseUrls: ["news.qq.com"] },
    { company: "Sina News", baseUrls: ["news.sina.com.cn"] },
    { company: "NetEase News", baseUrls: ["news.163.com"] },
    { company: "Phoenix TV", baseUrls: ["www.ifeng.com"] },
] as const;

/** news sites in Denmark */
export const DANISH_NEWS = [
    { company: "Politiken", baseUrls: ["www.politiken.dk"] },
    { company: "Berlingske", baseUrls: ["www.berlingske.dk"] },
    { company: "Jyllands-Posten", baseUrls: ["jyllands-posten.dk"] },
    { company: "Ekstra Bladet", baseUrls: ["ekstrabladet.dk"] },
    { company: "Information", baseUrls: ["www.information.dk"] },
    { company: "BT", baseUrls: ["www.bt.dk"] },
    { company: "Weekendavisen", baseUrls: ["www.weekendavisen.dk"] },
    { company: "Fyens Stiftstidende", baseUrls: ["fyens.dk"] },
    { company: "Kristeligt Dagblad", baseUrls: ["www.kristeligt-dagblad.dk"] },
    { company: "Copenhagen Post", baseUrls: ["cphpost.dk"] },
    { company: "Nordjyske Stiftstidende", baseUrls: ["nordjyske.dk"] },
    { company: "Århus Stiftstidende", baseUrls: ["stiften.dk"] },
    { company: "Dagbladet Børsen", baseUrls: ["borsen.dk"] },
    { company: "Lokalavisen", baseUrls: ["lokalavisen.dk"] },
    { company: "TV2 Nyheder", baseUrls: ["tv2.dk"] },
    { company: "DR Nyheder", baseUrls: ["dr.dk"] },
    { company: "Avisen Danmark", baseUrls: ["avisen.dk"] },
    { company: "Fagbladet 3F", baseUrls: ["fagbladet3f.dk"] },
    { company: "Herning Folkeblad", baseUrls: ["herningfolkeblad.dk"] },
    { company: "Midtjyllands Avis", baseUrls: ["midtjyllandsavis.dk"] },
] as const;

export const SWISS_NEWS = [
    { company: "Neue Zürcher Zeitung (NZZ)", baseUrls: ["www.nzz.ch"], type: ["newspaper", "digital"] },
    { company: "Swissinfo", baseUrls: ["www.swissinfo.ch"], type: ["digital-first"] },
    { company: "20 Minuten", baseUrls: ["www.20min.ch"], type: ["newspaper", "digital"] },
    { company: "Blick", baseUrls: ["www.blick.ch"], type: ["newspaper", "digital"] },
    { company: "Le Temps", baseUrls: ["www.letemps.ch"], type: ["newspaper", "digital"] },
    { company: "Tages-Anzeiger", baseUrls: ["www.tagesanzeiger.ch"], type: ["newspaper", "digital"] },
    { company: "SRF News", baseUrls: ["www.srf.ch"], type: ["television", "radio", "digital"] },
    { company: "Luzerner Zeitung", baseUrls: ["www.luzernerzeitung.ch"], type: ["newspaper", "digital"] },
    { company: "La Tribune de Genève", baseUrls: ["www.tdg.ch"], type: ["newspaper", "digital"] },
    { company: "Aargauer Zeitung", baseUrls: ["www.aargauerzeitung.ch"], type: ["newspaper", "digital"] },
    { company: "24 Heures", baseUrls: ["www.24heures.ch"], type: ["newspaper", "digital"] },
    { company: "Radio Télévision Suisse (RTS)", baseUrls: ["www.rts.ch"], type: ["television", "radio", "digital"] },
    { company: "Der Bund", baseUrls: ["www.derbund.ch"], type: ["newspaper", "digital"] },
    { company: "Schweizer Radio und Fernsehen (SRF)", baseUrls: ["www.srf.ch"], type: ["television", "radio", "digital"] },
    { company: "Basler Zeitung", baseUrls: ["www.bazonline.ch"], type: ["newspaper", "digital"] },
    { company: "Handelszeitung", baseUrls: ["www.handelszeitung.ch"], type: ["newspaper", "digital"] },
    { company: "Watson", baseUrls: ["www.watson.ch"], type: ["digital-first"] },
    { company: "Le Matin", baseUrls: ["www.lematin.ch"], type: ["newspaper", "digital"] },
    { company: "La Liberté", baseUrls: ["www.laliberte.ch"], type: ["newspaper", "digital"] },
    { company: "The Swiss Times", baseUrls: ["www.theswisstimes.ch"], type: ["digital-first"] },
] as const;

export const AUSTRALIAN_NEWS = [
    { company: "ABC News", baseUrls: ["www.abc.net.au"], type: ["television", "radio", "digital"] },
    { company: "The Sydney Morning Herald", baseUrls: ["www.smh.com.au"], type: ["newspaper", "digital"] },
    { company: "The Australian", baseUrls: ["www.theaustralian.com.au"], type: ["newspaper", "digital"] },
    { company: "Herald Sun", baseUrls: ["www.heraldsun.com.au"], type: ["newspaper", "digital"] },
    { company: "9News", baseUrls: ["www.9news.com.au"], type: ["television", "digital"] },
    { company: "SBS News", baseUrls: ["www.sbs.com.au"], type: ["television", "digital", "multicultural"] },
    { company: "The Age", baseUrls: ["www.theage.com.au"], type: ["newspaper", "digital"] },
    { company: "Sky News Australia", baseUrls: ["www.skynews.com.au"], type: ["television", "digital"] },
    { company: "Australian Financial Review", baseUrls: ["www.afr.com"], type: ["newspaper", "digital"] },
    { company: "news.com.au", baseUrls: ["www.news.com.au"], type: ["digital-first"] },
    { company: "The Courier-Mail", baseUrls: ["www.couriermail.com.au"], type: ["newspaper", "digital"] },
    { company: "7NEWS", baseUrls: ["7news.com.au"], type: ["television", "digital"] },
    { company: "The West Australian", baseUrls: ["www.thewest.com.au"], type: ["newspaper", "digital"] },
    { company: "Daily Telegraph", baseUrls: ["www.dailytelegraph.com.au"], type: ["newspaper", "digital"] },
    { company: "Guardian Australia", baseUrls: ["www.theguardian.com/au"], type: ["digital-first"] },
    { company: "Crikey", baseUrls: ["www.crikey.com.au"], type: ["digital-first", "independent"] },
    { company: "AAP (Australian Associated Press)", baseUrls: ["www.aap.com.au"], type: ["news agency", "digital"] },
    { company: "NT News", baseUrls: ["www.ntnews.com.au"], type: ["newspaper", "digital"] },
    { company: "The Canberra Times", baseUrls: ["www.canberratimes.com.au"], type: ["newspaper", "digital"] },
    { company: "Brisbane Times", baseUrls: ["www.brisbanetimes.com.au"], type: ["digital-first"] },
] as const;

export const JAPANESE_NEWS = [
    { company: "The Asahi Shimbun", baseUrls: ["www.asahi.com"], type: ["newspaper", "digital"] },
    { company: "Yomiuri Shimbun", baseUrls: ["www.yomiuri.co.jp"], type: ["newspaper", "digital"] },
    { company: "Nikkei", baseUrls: ["www.nikkei.com"], type: ["newspaper", "digital"] },
    { company: "Mainichi Shimbun", baseUrls: ["mainichi.jp"], type: ["newspaper", "digital"] },
    { company: "Kyodo News", baseUrls: ["www.kyodonews.jp"], type: ["news agency", "digital"] },
    { company: "Japan Times", baseUrls: ["www.japantimes.co.jp"], type: ["newspaper", "digital"] },
    { company: "NHK", baseUrls: ["www.nhk.or.jp"], type: ["television", "radio", "digital"] },
    { company: "Fuji News Network (FNN)", baseUrls: ["www.fnn.jp"], type: ["television", "digital"] },
    { company: "Sankei Shimbun", baseUrls: ["www.sankei.com"], type: ["newspaper", "digital"] },
    { company: "Toyo Keizai", baseUrls: ["www.toyokeizai.net"], type: ["digital", "business magazine"] },
    { company: "Hokkaido Shimbun", baseUrls: ["www.hokkaido-np.co.jp"], type: ["newspaper", "digital"] },
    { company: "Shizuoka Shimbun", baseUrls: ["www.at-s.com"], type: ["newspaper", "digital"] },
    { company: "Tokyo Shimbun", baseUrls: ["www.tokyo-np.co.jp"], type: ["newspaper", "digital"] },
    { company: "Yahoo Japan News", baseUrls: ["news.yahoo.co.jp"], type: ["digital-first"] },
    { company: "TBS News", baseUrls: ["news.tbs.co.jp"], type: ["television", "digital"] },
    { company: "Nippon TV News 24 Japan", baseUrls: ["www.news24.jp"], type: ["television", "digital"] },
    { company: "Jiji Press", baseUrls: ["www.jiji.com"], type: ["news agency", "digital"] },
    { company: "TV Asahi News", baseUrls: ["news.tv-asahi.co.jp"], type: ["television", "digital"] },
    { company: "WOWOW Prime News", baseUrls: ["www.wowow.co.jp"], type: ["television", "digital"] },
    { company: "Kansai Telecasting Corporation (KTV)", baseUrls: ["www.ktv.jp"], type: ["television", "digital"] },
] as const;

export const SOUTH_KOREAN_NEWS = [
    { company: "Yonhap News Agency", baseUrls: ["www.yonhapnews.co.kr"], type: ["news agency", "digital"] },
    { company: "The Korea Herald", baseUrls: ["www.koreaherald.com"], type: ["newspaper", "digital"] },
    { company: "The Korea Times", baseUrls: ["www.koreatimes.co.kr"], type: ["newspaper", "digital"] },
    { company: "Chosun Ilbo", baseUrls: ["www.chosun.com"], type: ["newspaper", "digital"] },
    { company: "JoongAng Ilbo", baseUrls: ["www.joongang.co.kr"], type: ["newspaper", "digital"] },
    { company: "Dong-A Ilbo", baseUrls: ["www.donga.com"], type: ["newspaper", "digital"] },
    { company: "MBC News", baseUrls: ["www.imnews.imbc.com"], type: ["television", "digital"] },
    { company: "SBS News", baseUrls: ["news.sbs.co.kr"], type: ["television", "digital"] },
    { company: "KBS News", baseUrls: ["news.kbs.co.kr"], type: ["television", "radio", "digital"] },
    { company: "Hankyoreh", baseUrls: ["english.hani.co.kr"], type: ["newspaper", "digital"] },
    { company: "Maeil Business Newspaper", baseUrls: ["www.mk.co.kr"], type: ["newspaper", "digital"] },
    { company: "MoneyToday", baseUrls: ["www.mt.co.kr"], type: ["digital-first", "business"] },
    { company: "Seoul Shinmun", baseUrls: ["www.seoul.co.kr"], type: ["newspaper", "digital"] },
    { company: "OhmyNews", baseUrls: ["www.ohmynews.com"], type: ["digital-first"] },
    { company: "News1 Korea", baseUrls: ["www.news1.kr"], type: ["news agency", "digital"] },
    { company: "Asia Business Daily", baseUrls: ["www.asiae.co.kr"], type: ["newspaper", "digital"] },
    { company: "Herald Business", baseUrls: ["biz.heraldcorp.com"], type: ["newspaper", "digital"] },
    { company: "eDaily", baseUrls: ["www.edaily.co.kr"], type: ["digital-first", "business"] },
    { company: "Seoul Economic Daily", baseUrls: ["www.sedaily.com"], type: ["newspaper", "digital"] },
    { company: "JTBC News", baseUrls: ["news.jtbc.co.kr"], type: ["television", "digital"] },
] as const;

export const TURKISH_NEWS = [
    { company: "Anadolu Agency (AA)", baseUrls: ["www.aa.com.tr"], type: ["news agency", "digital"] },
    { company: "Hürriyet", baseUrls: ["www.hurriyet.com.tr"], type: ["newspaper", "digital"] },
    { company: "Sabah", baseUrls: ["www.sabah.com.tr"], type: ["newspaper", "digital"] },
    { company: "Milliyet", baseUrls: ["www.milliyet.com.tr"], type: ["newspaper", "digital"] },
    { company: "TRT World", baseUrls: ["www.trtworld.com"], type: ["television", "digital"] },
    { company: "CNN Türk", baseUrls: ["www.cnnturk.com"], type: ["television", "digital"] },
    { company: "Sozcu", baseUrls: ["www.sozcu.com.tr"], type: ["newspaper", "digital"] },
    { company: "Daily Sabah", baseUrls: ["www.dailysabah.com"], type: ["newspaper", "digital"] },
    { company: "Yeni Şafak", baseUrls: ["www.yenisafak.com"], type: ["newspaper", "digital"] },
    { company: "Habertürk", baseUrls: ["www.haberturk.com"], type: ["television", "digital"] },
    { company: "BirGün", baseUrls: ["www.birgun.net"], type: ["newspaper", "digital"] },
    { company: "Türkiye Gazetesi", baseUrls: ["www.turkiyegazetesi.com.tr"], type: ["newspaper", "digital"] },
    { company: "Cumhuriyet", baseUrls: ["www.cumhuriyet.com.tr"], type: ["newspaper", "digital"] },
    { company: "Diken", baseUrls: ["www.diken.com.tr"], type: ["digital-first"] },
    { company: "NTV", baseUrls: ["www.ntv.com.tr"], type: ["television", "digital"] },
    { company: "Ensonhaber", baseUrls: ["www.ensonhaber.com"], type: ["digital-first"] },
    { company: "T24", baseUrls: ["www.t24.com.tr"], type: ["digital-first"] },
    { company: "Karar", baseUrls: ["www.karar.com"], type: ["newspaper", "digital"] },
    { company: "Gazete Duvar", baseUrls: ["www.gazeteduvar.com.tr"], type: ["digital-first"] },
    { company: "Bloomberg HT", baseUrls: ["www.bloomberght.com"], type: ["television", "digital"] },
] as const;

export const NORWEGIAN_NEWS = [
    { company: "Aftenposten", baseUrls: ["www.aftenposten.no"], type: ["newspaper", "digital"] },
    { company: "Verdens Gang (VG)", baseUrls: ["www.vg.no"], type: ["newspaper", "digital"] },
    { company: "Dagbladet", baseUrls: ["www.dagbladet.no"], type: ["newspaper", "digital"] },
    { company: "NRK", baseUrls: ["www.nrk.no"], type: ["television", "radio", "digital"] },
    { company: "Dagens Næringsliv", baseUrls: ["www.dn.no"], type: ["newspaper", "digital"] },
    { company: "Nettavisen", baseUrls: ["www.nettavisen.no"], type: ["digital-first"] },
    { company: "Klassekampen", baseUrls: ["www.klassekampen.no"], type: ["newspaper", "digital"] },
    { company: "Morgenbladet", baseUrls: ["www.morgenbladet.no"], type: ["newspaper", "digital"] },
    { company: "E24", baseUrls: ["www.e24.no"], type: ["digital-first", "business"] },
    { company: "TV2", baseUrls: ["www.tv2.no"], type: ["television", "digital"] },
    { company: "Bergens Tidende", baseUrls: ["www.bt.no"], type: ["newspaper", "digital"] },
    { company: "Adresseavisen", baseUrls: ["www.adressa.no"], type: ["newspaper", "digital"] },
    { company: "Stavanger Aftenblad", baseUrls: ["www.aftenbladet.no"], type: ["newspaper", "digital"] },
    { company: "Fædrelandsvennen", baseUrls: ["www.fvn.no"], type: ["newspaper", "digital"] },
    { company: "ABC Nyheter", baseUrls: ["www.abcnyheter.no"], type: ["digital-first"] },
    { company: "Romerikes Blad", baseUrls: ["www.rb.no"], type: ["newspaper", "digital"] },
    { company: "Sunnmørsposten", baseUrls: ["www.smp.no"], type: ["newspaper", "digital"] },
    { company: "Finansavisen", baseUrls: ["www.finansavisen.no"], type: ["newspaper", "digital"] },
    { company: "Nordlys", baseUrls: ["www.nordlys.no"], type: ["newspaper", "digital"] },
    { company: "Hamar Arbeiderblad", baseUrls: ["www.h-a.no"], type: ["newspaper", "digital"] },
] as const;
