// runtime type-check shim exports
export type Abs<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Acceleration<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AccelerationUom<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Add<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AfterFirst<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AlphaChar<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AmazonUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AmericanExpress<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type And<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AnyFunction<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AnyObject<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Api<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AppleUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Area<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AreaUom<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ArrayTypeDefn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type As<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsApi<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsArray<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsDateMeta<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsDoneFn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsDropResult<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsEscapeFunction<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsFourDigitYear<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsFromTo<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsHtmlComponentTag<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsHtmlTag<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsNarrowingFn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsNestingApi<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsNestingConfig<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsNumber<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsOptionalParamFn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsOutputToken<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsRecord<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsRgbObject<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsRgbTuple<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsRgbaObject<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsSimpleType<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsStaticFn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsString<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsTakeState<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsTwoDigitMonth<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AsTypeSubtype<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type AustralianNewsUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type BeforeLast<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type BelgianNewsUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type BestBuyUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type BooleanLike<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type BracketNesting<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Brand<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CamelCase<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CanadianNewsUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Chars<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ChineseNewsUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ColorFnOptOpacity<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ColorFnValue<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Comparator<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ComparatorOperation<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Compare<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Comparison<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ComparisonAccept<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ComparisonOperation<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Container<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Contains<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ConvertTypeOf<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ConverterDefn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CostCoUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CreditCard<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CssAspectRatio<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CssClassSelector<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CssColorFn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CssColorSpace<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CssDefinition<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CssIdSelector<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CssKeyframeTimestamp<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CssNamedColor<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CssNamedColorLookup<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CssPseudoClass<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CssRgb<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CssSelector<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CssTagSelector<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Csv<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CsvToJsonTuple<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CsvToTuple<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CsvToTupleStr<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Current<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CurrentUom<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type CvsUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DanishNewsUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DateLike<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DateMeta<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DatePlus<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DayJsLike<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DayOfWeek<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DaysInMonth<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Decrement<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DefaultNesting<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DefineObject<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DefineObjectWith<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DefineTokenDetail<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DefineTuple<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Defined<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DellUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Dictionary<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DictionaryTypeDefn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Distance<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DistanceUom<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DomainName<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DotPathFor<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DropParser<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DropParserFn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DropParserKv<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DropResult<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DropRule<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DropRulePolicy<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DutchNewsUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type DynamicTokenApi<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type EachAsString<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type EbayUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Email<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Empty<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type EmptyObject<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type EndsWith<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Energy<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type EnergyUom<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type EnsureLeading<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type EnsureSurround<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type EnsureTrailing<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type EpochInMs<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type EpochInSeconds<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Err<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ErrMsg<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type EtsyUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type EvenNumber<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Every<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Expand<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ExpandDictionary<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ExpandRecursively<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Extends<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Fallback<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FalsyValue<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FifoQueue<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Filter<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FilterFn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FinalizedDropRule<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Find<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FindFunction<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type First<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FirstChar<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FixedLengthArray<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FnArgsDefn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FnKeyValue<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FnPropertiesDefn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FnReturnTypeDefn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FnWithProps<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FourDigitYear<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FrenchNewsUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Frequency<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FrequencyUom<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FromCsv<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FromDefineObject<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FromDefn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FromInputToken<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FromInputToken__Object<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FromInputToken__String<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FromKv<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FromTo<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type FromWideTokens<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GermanNewsUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Get<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GetComparisonParams<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GetEach<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GetMonthAbbrev<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GetMonthName<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GetMonthNumber<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GetPhoneCountryCode<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GetSeason<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GetTypeOf<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GetUrlDynamics<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GetUrlPath<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GetUrlPort<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GetUrlProtocol<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GetUrlProtocolPrefix<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GetUrlQueryParams<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GetUrlSource<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GetYear<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GetYouTubePageType<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GithubOrgUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GithubRepoIssueUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GithubRepoIssuesListUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GithubRepoProjectUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GithubRepoProjectsUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GithubRepoReleaseTagUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GithubRepoReleasesUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GithubRepoUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type GithubUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type HandMUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type HandleDoneFn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type HasUnionType<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Hemisphere<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type HexColor<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type HomeDepotUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Html__AtomicTag<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Html__BlockTag<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IT_TakeArray<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IT_TakeOutcome<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IanaZone<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type If<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IfLength<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IkeaUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Immutable<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Increment<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IndexOf<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Indexable<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IndianNewsUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type InlineSvg<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type InputToken<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type InputTokenSuggestions<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Integer<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Intersection<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Ip4Address<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Ip6Address<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Ip6GroupExpansion<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Ip6Subnet<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsAfter<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsAny<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsArray<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsBefore<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsBetweenExclusively<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsBetweenInclusively<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsBoolean<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsContainer<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsCssRgbString<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsDayJs<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsDictionary<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsDoubleLeap<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsEmpty<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsEqual<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsError<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsFalse<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsFalsy<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsFunction<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsGreaterThan<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsGreaterThanOrEqual<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsHexColor<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsInteger<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsIp4Address<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsIp6Address<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsIpAddress<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsJsDate<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsLeapYear<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsLessThan<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsLessThanOrEqual<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsLiteralLike<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsLuxonDateTime<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsMoment<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsNegativeNumber<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsNever<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsNonEmptyObject<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsNull<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsNumber<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsObjectKeyRequiringQuotes<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsSameDay<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsSameMonth<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsSameMonthYear<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsScalar<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsSingleChar<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsStaticFn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsString<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsTemplateLiteral<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsTrue<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsUndefined<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsUnion<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsUnionArray<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsValidIndex<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsWideObject<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsWideString<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsWideType<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Iso3166Alpha2Lookup<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Iso3166Alpha3Lookup<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Iso3166CodeLookup<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Iso3166CountryLookup<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Iso3166_1_Alpha2<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Iso3166_1_Alpha3<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Iso3166_1_CountryCode<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Iso3166_1_CountryName<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsoDate<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsoDateTime<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsoMonthDate<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsoTimeLike<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsoYear<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type IsoYearMonth<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ItalianNewsUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type JapaneseNewsUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Join<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type KebabCase<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type KeyOf<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type KeyValue<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Keys<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type KeysWithError<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type KnownNestingConfig<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type KrogerUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Last<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type LastChar<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type LeftRight<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type LeftWhitespace<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Length<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type LessThan<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type LessThanOrEqual<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type LexerState<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type LifoQueue<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type LikeRegExp<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type LogicFunction<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type LogicalReturns<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type LowerAlphaChar<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type LowesUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Luminosity<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type LuminosityUom<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type LuxonLikeDateTime<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type MacysUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type MakeKeysOptional<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type MakeKeysRequired<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type MapKeyDefn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type MapValueDefn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Mass<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type MassUom<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Mastercard<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type MergeObjects<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type MergeScalars<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type MergeTuples<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Metric<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type MetricCategory<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type MexicanNewsUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type MinimalDigitDate<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type MomentLike<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type MonthAbbrev<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type MonthName<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Mutable<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type NBSP<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type NarrowObject<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Narrowable<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type NestedSplit<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type NestedSplitPolicy<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Nesting<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type NestingApi<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type NestingKeyValue<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type NestingTuple<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type NetworkProtocol<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type NetworkProtocolPrefix<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type NewsUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type NikeUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type NoMatch<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type NorwegianNewsUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Not<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Nothing<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type NumberLike<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type NumericChar<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ObjectApiCallback<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ObjectKey<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ObjectKeys<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ObjectToApi<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type OddNumber<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type OnPass<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Opt<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type OptSpace<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type OptionalParamFn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Or<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ParameterlessFn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ParamsForComparison<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ParseDate<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ParsedDate<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type PascalCase<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type PathJoin<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type PhoneNumber<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type PhoneNumberWithCountryCode<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Pluralize<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Power<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type PowerUom<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Precision<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Pressure<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type PressureUom<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type QuoteNesting<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RGB<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RGBA<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RecordValueTypeDefn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RegexHandlingStrategy<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RegularExpression<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RemoveIndex<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RemoveNever<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RemovePhoneCountryCode<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Replace<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ReplaceAll<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ReplaceAllFromTo<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RepoSource<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RepoUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RequiredKeys<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Resistance<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ResistanceUom<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RestMethod<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RetailUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RetainAfter<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RetainChars<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RetainUntil<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RetainUntil__Nested<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RetainUntil__NestedOptions<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RetainWhile<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Reverse<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ReverseLookup<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RgbColor<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RgbDecimalString<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RgbTuple<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RightWhitespace<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RuntimeType__Atomic<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type RuntimeUnion<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SafeDecode<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SafeEncode<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SafeEncodingGroup<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SafeEncodingKey<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Scalar<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Second<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SemanticVersion<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Set<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Shape<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ShapeApi<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ShapeCallback<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ShapeTupleOrUnion<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SharedKeys<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SimpleContainerToken<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SimpleScalarToken<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SimpleToken<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SimpleType<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Slice<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SliceArray<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SnakeCase<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SocialMediaUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Some<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SomeEqual<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SortByKey<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SortByKeyOptions<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SortByLength<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SouthKoreanNewsUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SpanishNewsUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Speed<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SpeedUom<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Split<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type StartsWith<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type StaticTokenApi<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type StringKeys<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type StripAfter<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type StripAfterLast<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type StripBefore<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type StripChars<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type StripLeading<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type StripSurround<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type StripTrailing<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type StripUntil<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type StripWhile<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Suggest<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Surround<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type SwissNewsUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TT_Atomic<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TT_Container<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TT_Function<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TT_Set<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TT_Singleton<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TakeFunction<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TakeParser<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TakeStart<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TakeStartFn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TakeStartMatches<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TakeState<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TakeWrapper<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TargetUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Temperature<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TemperatureUom<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TemporalLike<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Thenable<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ThreeDigitMillisecond<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TimeMetric<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TimeUom<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TimezoneOffset<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ToJson<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ToJsonOptions<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ToKv<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ToLiteralOptions<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ToNumber<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ToNumericArray<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ToString<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ToStringArray<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ToStringLiteral<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ToStringLiteral__Array<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ToStringLiteral__Object<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Token<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TokenName<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TokenSyntax<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TokenType<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Trim<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TrimEnd<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TrimStart<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Truncate<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Tuple<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TupleToUnion<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TurkishNewsUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TwChromaLookup<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TwColor<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TwColorOptionalOpacity<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TwColorTarget<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TwColorWithLuminosity<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TwColorWithLuminosityOpacity<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TwHue<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TwLuminosity<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TwLuminosityLookup<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TwModifier<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TwTarget__Color<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TwTarget__Color__Light<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TwoDigitDate<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TwoDigitHour<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TwoDigitMinute<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TwoDigitMonth<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TwoDigitSecond<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TypeOf<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TypeSubtype<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TypeTokenAtomics<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TypeTokenKind<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TypeTokenSets<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TypeTokenSingletons<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TypeTuple<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TypedError<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type TypedFunction<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type UkNewsUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Unbrand<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type UnionArrayToTuple<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type UnionFilter<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type UnionToTuple<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Unique<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type UniqueKeys<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Unset<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Uom<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type UpdateTake<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type UpperAlphaChar<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Uri<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type UrlPath<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type UrlsFrom<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type UsNewsUrls<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type UsPhoneNumber<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type UsStateAbbrev<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type UsStateName<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ValueCallback<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Values<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Variable<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Visa<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type VisaMastercard<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Voltage<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type VoltageUom<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Volume<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type VolumeUom<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type VueRef<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type WalgreensUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type WalmartUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type WayFairUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type WeakMapKeyDefn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type WeakMapValueDefn<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Whitespace<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type WholeFoodsUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type WideTokenNames<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Widen<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type WithKeys<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type WithValue<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type WithoutKeys<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type WithoutValue<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type YouTubeCreatorUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type YouTubeEmbedUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type YouTubeFeedType<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type YouTubeFeedUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type YouTubePageType<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type YouTubePlaylistUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type YouTubeShareUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type YouTubeUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type YouTubeVideoUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type YouTubeVideosInPlaylist<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ZaraUrl<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type Zip5<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ZipCode<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export type ZipPlus4<A = any, B = any, C = any, D = any, E = any, F = any, G = any, H = any, I = any, J = any, K = any, L = any> = any;
export declare const isNamedNestingConfig: any;
// end runtime type-check shim exports
export declare const ShapeApiImplementation: any;
export declare const afterFirst: any;
export declare const asArray: any;
export declare const asChars: any;
export declare const asDate: any;
export declare const asDateTime: any;
export declare const asNumber: any;
export declare const asString: any;
export declare const asTakeState: any;
export declare const asTwoDigitMonth: any;
export declare const asTypeSubtype: any;
export declare const asTypedError: any;
export declare const capitalize: any;
export declare const compare: any;
export declare const contains: any;
export declare const convertCssRgbStringToRgbObject: any;
export declare const createEncoder: any;
export declare const createErrorCondition: any;
export declare const createFnWithProps: any;
export declare const createStaticTakeFunction: any;
export declare const createTakeFunction: any;
export declare const createTakeWhileFunction: any;
export declare const createTemplateRegExp: any;
export declare const defineObject: any;
export declare const doesExtend: any;
export declare const ensureLeading: any;
export declare const ensureTrailing: any;
export declare const equalsSome: any;
export declare const err: any;
export declare const fallback: any;
export declare const filter: any;
export declare const find: any;
export declare const firstChar: any;
export declare const fromDefineObject: any;
export declare const fromInputToken: any;
export declare const get: any;
export declare const getEach: any;
export declare const getInputToken: any;
export declare const getMonthAbbrev: any;
export declare const getMonthNumber: any;
export declare const getPhoneCountryCode: any;
export declare const getTailwindModifiers: any;
export declare const getTokenKind: any;
export declare const getUrlPath: any;
export declare const getUrlQueryParams: any;
export declare const handleDoneFn: any;
export declare const hasDefaultValue: any;
export declare const hasIndexOf: any;
export declare const hasOnlyStringKeys: any;
export declare const hasOverlappingKeys: any;
export declare const hasProtocol: any;
export declare const hasUrlQueryParameter: any;
export declare const hexColorToRgbObject: any;
export declare const ifArray: any;
export declare const ifLowercaseChar: any;
export declare const ifNotNull: any;
export declare const indexOf: any;
export declare const infer: any;
export declare const isAfter: any;
export declare const isAlpha: any;
export declare const isApi: any;
export declare const isApiSurface: any;
export declare const isArray: any;
export declare const isAtomicKind: any;
export declare const isBoolean: any;
export declare const isConstant: any;
export declare const isContainer: any;
export declare const isCssNamedColor: any;
export declare const isCssRgbString: any;
export declare const isCsv: any;
export declare const isDateMeta: any;
export declare const isDefineObject: any;
export declare const isDefineTuple: any;
export declare const isDefined: any;
export declare const isDictionary: any;
export declare const isDomainName: any;
export declare const isDoneFn: any;
export declare const isDoubleLeap: any;
export declare const isEmpty: any;
export declare const isEqual: any;
export declare const isErr: any;
export declare const isError: any;
export declare const isFalse: any;
export declare const isFunction: any;
export declare const isHexColor: any;
export declare const isIndexable: any;
export declare const isInputToken: any;
export declare const isInputToken__String: any;
export declare const isInteger: any;
export declare const isIp4Address: any;
export declare const isIp6Address: any;
export declare const isIpAddress: any;
export declare const isIso3166Alpha2: any;
export declare const isIso3166Alpha3: any;
export declare const isIso3166CountryName: any;
export declare const isLeapYear: any;
export declare const isMap: any;
export declare const isNarrowable: any;
export declare const isNarrowableArray: any;
export declare const isNegativeNumber: any;
export declare const isNestingEnd: any;
export declare const isNestingEndMatch: any;
export declare const isNestingKeyValue: any;
export declare const isNestingStart: any;
export declare const isNestingTuple: any;
export declare const isNotEmpty: any;
export declare const isNothing: any;
export declare const isNull: any;
export declare const isNumber: any;
export declare const isNumberLike: any;
export declare const isNumericString: any;
export declare const isObject: any;
export declare const isRef: any;
export declare const isRegExp: any;
export declare const isRgbObject: any;
export declare const isRgbaObject: any;
export declare const isSameTypeOf: any;
export declare const isScalar: any;
export declare const isSet: any;
export declare const isSetBasedKind: any;
export declare const isShape: any;
export declare const isSimpleContainerToken: any;
export declare const isSimpleScalarToken: any;
export declare const isSpecificConstant: any;
export declare const isStaticTemplate: any;
export declare const isString: any;
export declare const isSymbol: any;
export declare const isTailwindModifier: any;
export declare const isTakeState: any;
export declare const isTrue: any;
export declare const isTruthy: any;
export declare const isTwoDigitMonth: any;
export declare const isTypeSubtype: any;
export declare const isTypeToken: any;
export declare const isTypeTokenKind: any;
export declare const isUndefined: any;
export declare const isUnset: any;
export declare const isUrl: any;
export declare const isVariable: any;
export declare const isWeakMap: any;
export declare const isYouTubeCreatorUrl: any;
export declare const isYouTubeFeedUrl: any;
export declare const isYouTubeShareUrl: any;
export declare const isYouTubeUrl: any;
export declare const isYouTubeVideoUrl: any;
export declare const isYouTubeVideosInPlaylist: any;
export declare const keysOf: any;
export declare const keysWithError: any;
export declare const last: any;
export declare const lowercase: any;
export declare const mutable: any;
export declare const nestedSplit: any;
export declare const parseDate: any;
export declare const parseDateObject: any;
export declare const parseIsoDate: any;
export declare const parseNumericDate: any;
export declare const removeTailwindModifiers: any;
export declare const removeUrlProtocol: any;
export declare const retainAfter: any;
export declare const retainAfterInclusive: any;
export declare const retainChars: any;
export declare const retainKeys: any;
export declare const retainUntil__Nested: any;
export declare const retainWhile: any;
export declare const reverseLookup: any;
export declare const rightWhitespace: any;
export declare const simpleType: any;
export declare const slice: any;
export declare const sortByKey: any;
export declare const split: any;
export declare const startsWithTypeguard: any;
export declare const stripAfter: any;
export declare const stripBefore: any;
export declare const stripChars: any;
export declare const stripLeading: any;
export declare const stripSurround: any;
export declare const stripTrailing: any;
export declare const stripWhile: any;
export declare const toAllCaps: any;
export declare const toKebabCase: any;
export declare const toPascalCase: any;
export declare const toStringLiteral: any;
export declare const toStringLiteral__Object: any;
export declare const toStringLiteral__Tuple: any;
export declare const toStringToken: any;
export declare const unset: any;
export declare const validHtmlAttributes: any;
export declare const valuesOf: any;
