name: Publish
on:
  push:
    tags:
        - 'v*'

jobs:

  publish:
    uses: yankeeinlondon/gha/.github/workflows/publish.yml@main
    with:
      jsr_scope: '@yankeeinlondon'
      github_packages_scope: '@yankeeinlondon'
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      JSR_TOKEN: ${{ secrets.JSR_TOKEN }}
